server:
  port: 9090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats-db}
    username: ${SPRING_DATASOURCE_USERNAME:stats-user}
    password: ${SPRING_DATASOURCE_PASSWORD:stats-root}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-location: classpath:schema.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
